# This is an example of how to run the backend in production using secret files
# and using the image from GitHub Packages.

name: olillin-com

services:
    server:
        image: 'ghcr.io/olillin/olillin.com:latest'
        container_name: olillin-com-server
        restart: always

        ports:
            - '3000:3000'
